### ISSUE TITLE
Improve command feedback to user

### ISSUE THREAD

**Issue by Matilda-Yxx** [CS2103JAN2017-W10-B1/main#89]
- Undo command "undo last task successfully" (which task? Want to redo?)
- Add in a task - want to edit details?
- List tasks under a list: what commands can you use to organize the tasks?

**Comment by wangzexin** [comment]
Add feedback message "you are done for today!" when there is no tasks due today Abandoned

**Comment by wangzexin** [comment]
Add feedback message "you can type redo to revert the undo command" for each undo command
